"""Assembler: структура+токены -> статический HTML (<2с, mobile-first) + SEO-layer.
Контент пока placeholder (реальный через Claude-агент когда подключим ключ)."""
import json,html
SECTION_TITLES={"toplist":"Top {brand} Sites {geo}","comparison":"Compare Top Casinos",
 "why_trust":"Why Trust Our Picks","payout_speed":"Fastest Payout Casinos","games":"Popular Games",
 "bonuses":"Best Bonuses","faq":"Frequently Asked Questions","how_to_choose":"How to Choose",
 "reviews":"Player Reviews"}
def faq_schema(brand):
    qs=[(f"Is {brand} safe?",f"{brand} is reviewed for licensing, payout speed and game fairness."),
        (f"How fast are {brand} payouts?","Withdrawals are typically processed within 24 hours.")]
    return {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[
        {"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in qs]}
def render(plan):
    p=plan; pal=p["palette"]; fh,fb=p["fonts"]
    secs=[]
    for s in p["sections"]:
        title=SECTION_TITLES.get(s,s).format(brand=p["brand"],geo=p["geo"].upper())
        if s=="toplist":
            body="".join(f'<div class="card"><b>{p["brand"]} #{i}</b><a class="cta" href="/go/">{p["cta"]}</a></div>' for i in range(1,4))
        elif s=="faq":
            body='<details><summary>Is it safe?</summary><p>Reviewed for licensing & payouts.</p></details>'
        else:
            body=f'<p>[{s}] content for {p["brand"]} in {p["geo"]} — generated by content-agent.</p>'
        secs.append(f'<section><h2>{html.escape(title)}</h2>{body}</section>')
    css=f"""*{{box-sizing:border-box}}body{{margin:0;background:{pal['bg']};color:{pal['fg']};font-family:{fb};line-height:1.6}}
h1,h2{{font-family:{fh}}}.wrap{{max-width:860px;margin:0 auto;padding:16px}}
section{{background:{pal['card']};border-radius:{p['radius']};padding:18px;margin:14px 0}}
.cta{{display:inline-block;background:{pal['accent']};color:#000;padding:10px 18px;border-radius:{p['radius']};text-decoration:none;font-weight:700;margin-top:8px}}
.card{{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #ffffff22;padding:10px 0}}
.hero{{text-align:{'center' if p['hero']=='center' else 'left'};padding:40px 0}}"""
    schema=json.dumps(faq_schema(p["brand"]))
    return f"""<!doctype html><html lang="{p['geo']}"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(p['brand'])} — {html.escape(p['keyword'])} {p['geo'].upper()}</title>
<meta name="description" content="Best {html.escape(p['brand'])} review for {p['geo'].upper()}.">
<link rel="canonical" href="https://{p['domain']}/">
<script type="application/ld+json">{schema}</script>
<style>{css}</style></head><body><div class="wrap">
<header class="hero"><h1>{html.escape(p['keyword'])} — {html.escape(p['brand'])}</h1>
<a class="cta" href="/go/">{p['cta']}</a></header>
{''.join(secs)}
<footer><small>Design: {pal['name']} · layout: {p['hero']} · sections: {len(p['sections'])}</small></footer>
</div></body></html>"""
